version: "3"

services:

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp

    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      RAILS_ENV: development
volumes:
  db_data: