version: "3"

services:

  db:
    image: postgres

    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./2. Init Database:/docker-entrypoint-initdb.d/init.sql
      - .:/var/lib/postgresql/data
      
  web:
    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db