name: Test and Linter Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup app
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          RAILS_ENV: test
          API_KEY: ${{ secrets.API_KEY }}
          API_REFERENCE: ${{ secrets.API_REFERENCE }}
          CITY_ID: ${{ secrets.CITY_ID }}
          URL_API: ${{ secrets.URL_API }}
        run: make setup
        
      - name: Linter check
        run: make lint
        
      - name: Run Test
        env:
           API_KEY: ${{ secrets.API_KEY }}
           API_REFERENCE: ${{ secrets.API_REFERENCE }}
           CITY_ID: ${{ secrets.CITY_ID }}
           URL_API: ${{ secrets.URL_API }}
        run: make test
